apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-batik-frontend
  namespace: web-batik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-batik-frontend
  template:
    metadata:
      labels:
        app: web-batik-frontend
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
        searches:
          - web-batik.svc.cluster.local
          - svc.cluster.local
          - cluster.local
        options:
          - name: ndots
            value: "2"
      containers:
      - name: web-batik-frontend
        # Ganti ke image registry yang benar jika perlu
        image: 10.10.11.235:5000/frontend-web-batik:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 3050
        envFrom:
        - configMapRef:
            name: batik-configmap
        volumeMounts:
        - name: data
          mountPath: /app/public/storage
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-batik
---
apiVersion: v1
kind: Service
metadata:
  name: web-batik-frontend
  namespace: web-batik
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3050
  selector:
    app: web-batik-frontend
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: web-batik-ingress
  namespace: web-batik
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`rispro.umm.ac.id`)
    priority: 100
    services:
    - name: web-batik-frontend
      port: 80
  tls:
    secretName: tls-secret
    domains:
    - main: rispro.umm.ac.id
